name: Check Tickets
on:
  workflow_dispatch  # 只允許手動執行
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1
        with:
          product-id: 211782
          schedule-id: 100001
          seat-id: 10008
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }} 
          message: '자리잡아즉시 구매하세요.' 
